# Jekyll reads from ./content
source: content

# Layouts live at: content/_layouts
layouts_dir: _layouts

title: "Hyndland Primary Parent Council"
description: "Official website of the Hyndland Primary School Parent Council in Glasgow. News, events, fundraising and school community updates."
url: "https://hyndlandprimary.parent-council.scot"

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM

# Do NOT set collections_dir when using source: content
collections:
  news:
    output: true
    permalink: /news/:path/

  events:
    output: true
    permalink: /events/:path/

defaults:
  # All pages: default layout
  - scope:
      path: ""          # relative to 'source' (so this is inside /content)
      type: "pages"
    values:
      layout: default

  # Pages under /news/ (optional; keep only if you still have non-collection pages there)
  - scope:
      path: "news/"     # relative to 'source' → content/news/
      type: "pages"
    values:
      layout: news_article
      categories: ["News"]

  # Documents in the 'news' collection
  - scope:
      path: ""          # whole collection
      type: "news"      # ← use the collection label
    values:
      layout: news_article
      categories: ["News"]

  - scope:
      path: "events/"
      type: "events"
    values:
      layout: event
      categories: ["Events"]


pagination:
  trail:
    before: 2 # The number of links before the current page
    after: 2  #
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

gems:
  - jekyll-paginate-v2
